### ISSUE TITLE
 undefined reference to `__atomic_load_8'  while  building SampleApp on raspberryPi

### ISSUE THREAD

**Issue by Vaishnavikumara** [alexa/avs-device-sdk#1404]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment]
Hello Vaishnavikumara,

It looks very likely that this is a duplicate of [issue 380](https://github.com/alexa/avs-device-sdk/issues/380).  The fix reported there is to add:

`set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -latomic")`

...to CMakelists.txt.

best regards,
-SWH

**Comment by Chiggy-Playz** [comment]
@scotthea-amazon  I tried the fix you gave here. It still did not work. I am using rpi4 with debian 10.

**Comment by Xxjojo** [comment]
@Chiggy-Playz me too

**Comment by Chiggy-Playz** [comment]
> @Chiggy-Playz me too

you can solve the issue by going to the avs-sdk.../CMakeTextList.txt and then paste 
set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -latomic")

done for the atomic base error.

**Comment by angus390** [comment]
> > @Chiggy-Playz me too
> 
> you can solve the issue by going to the avs-sdk.../CMakeTextList.txt and then paste
> set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -latomic")
> 
> done for the atomic base error.

How do you get to this line? thanks

**Comment by coriolan-cs** [comment]
Same problem, where in the file do you need to add this line? Thanks

**Comment by Chiggy-Playz** [comment]
@coriolan-cs  you edited the wrong file. you had to edit the file in source/avs-sdk-device/CMakeTextList.txt and then add the file in the end @angus390 follow the same

**Comment by coriolan-cs** [comment]
Oh sorry about the confusion, I had this problem when building for Intel Realsense, not Alexa (I google the problem and arrived here)
Although I replaced source/avs-sdk-device/ by /librealsense/

**Comment by djcors** [comment]
i got a same error.
```
/usr/bin/ld: CMakeFiles/SampleApp.dir/SampleApplication.cpp.o: en la función `std::__atomic_base<unsigned long long>::operator=(unsigned long long)':
/usr/include/c++/8/bits/atomic_base.h:374: referencia a `__atomic_store_8' sin definir
/usr/bin/ld: CMakeFiles/SampleApp.dir/PortAudioMicrophoneWrapper.cpp.o: en la función `alexaClientSDK::avsCommon::utils::sds::SharedDataStream<alexaClientSDK::avsCommon::utils::sds::InProcessSDSTraits>::Writer::write(void const*, unsigned int, std::chrono::duration<long long, std::ratio<1ll, 1000ll> >)':
/usr/include/c++/8/bits/atomic_base.h:396: referencia a `__atomic_load_8' sin definir
/usr/bin/ld: CMakeFiles/SampleApp.dir/PortAudioMicrophoneWrapper.cpp.o: en la función `alexaClientSDK::avsCommon::utils::sds::SharedDataStream<alexaClientSDK::avsCommon::utils::sds::InProcessSDSTraits>::Writer::Writer(alexaClientSDK::avsCommon::utils::sds::WriterPolicy, std::shared_ptr<alexaClientSDK::avsCommon::utils::sds::SharedDataStream<alexaClientSDK::avsCommon::utils::sds::InProcessSDSTraits>::BufferLayout>)':
/usr/include/c++/8/bits/atomic_base.h:396: referencia a `__atomic_load_8' sin definir
/usr/bin/ld: CMakeFiles/SampleApp.dir/PortAudioMicrophoneWrapper.cpp.o: en la función `std::__atomic_base<unsigned long long>::operator unsigned long long() const':
/usr/include/c++/8/bits/atomic_base.h:396: referencia a `__atomic_load_8' sin definir
/usr/bin/ld: ../../ACL/src/libACL.so: referencia a `__atomic_fetch_add_8' sin definir
collect2: error: ld returned 1 exit status
make[3]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/build.make:288: SampleApp/src/SampleApp] Error 1
make[2]: *** [CMakeFiles/Makefile2:10227: SampleApp/src/CMakeFiles/SampleApp.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:10239: SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
```
My system:
```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"`
```
I try with
`set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -latomic")` 

at end of `~/avs-device-sdk/CMakeLists.txt` 

But not works for me

**Comment by Chiggy-Playz** [comment]
@djcors try putting it on the 9th line. That is just after the endif()

**Comment by kclchan** [comment]
This issue is fixed in v1.15 of the SDK.

**Comment by buddywhitman** [comment]
I have the latest SDK version but still faced the same issue.

**Comment by lombardian** [comment]
Yeeeehaaaa! It works. For newbies like me, you have to:

`cd avs-device-sdk`

then:

`nano CMakeLists.txt`

go to the bottom and add in the file:

`set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -latomic")`

**Comment by cwchawt200** [comment]
> sudo update-alternatives --set gcc "/usr/bin/gcc-5"

https://solarianprogrammer.com/2017/12/08/raspberry-pi-raspbian-install-gcc-compile-cpp-17-programs/

for Raspian 10 or above

**Comment by dusmit** [comment]
maybe you need use target_link_libraries(target atomic)

**Comment by YourArka** [comment]
> Hello Vaishnavikumara,
> 
> It looks very likely that this is a duplicate of [issue 380](https://github.com/alexa/avs-device-sdk/issues/380). The fix reported there is to add:
> 
> `set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -latomic")`
> 
> ...to CMakelists.txt.
> 
> best regards, -SWH

hello, this is not working
