### ISSUE TITLE
The Sensory TrulyHandsfree binaries license key has expired.

### ISSUE THREAD

**Issue by TaoGegithub** [alexa/avs-device-sdk#1482]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Provide the steps to reproduce the issue, if applicable:
sudo bash setup.sh config.json -s 998987

### What version of the AVS Device SDK are you using?
      <newest>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ yes ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ yes ] Other - tell us more: Raspbian Buster

From this link: [Sensory/alexa-rpi](https://github.com/Sensory/alexa-rpi), I found that "License key for 5.0.0-beta.10.2 expires 2019-08-27.", just as shown below

![image](https://user-images.githubusercontent.com/15697635/63823058-13b56880-c985-11e9-9c56-7a164b1216f7.png)

I confirm it leaded to "error: license key has expired"

Will the license key be renewed? Otherwise the AVS Device SDK won't work on Raspbian platform. 

Thanks a lot.

**Comment by timbeh** [comment]
Same problem here!

**Comment by timbeh** [comment]
I just checked on the repo. (https://github.com/Sensory/alexa-rpi)
If you take a look at the commits you can see that the Key was always renewed a day or 2 after it's expiry. I think this won't be a long-lasting issue.
<img width="786" alt="Screenshot 2019-08-28 at 11 11 59" src="https://user-images.githubusercontent.com/42168917/63842876-bf5eb880-c985-11e9-9b55-79f6a6933198.png">

**Comment by peatidge** [comment]
Same problem here, almost went crazy trying to figure out why Alexa was not responding. 
Tested mic, audio and then tried updating the licence using
sudo ./third-party/alexa-rpi/bin/license.sh
way to many times for my sanity :) 
In any case it appears this is the reason as it is the most recent issue posted.
Thanks for the confirmation TaoGegithub

**Comment by timbeh** [comment]
Good news! The issue has been resolved.
I contacted the developer and he has extended the license.
Everything should be working again, you can close this issue now. :)

**Comment by pablinho1023** [comment]
Hello I just got this problem, but how should I fix it? If I say yes I still get an error.

Thank you!
