### ISSUE TITLE
Got 'UNRECOVERABLE AUTHORIZATION ERROR: INVALID_REQUEST' when run sampleApp on 1.7

### ISSUE THREAD

**Issue by yexin123987** [alexa/avs-device-sdk#674]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When I first time run and  authorize sampleApp, I was able to get authorization code and registered successfully on https://amazon.com/us/code. Then I immediately got an error " UNRECOVERABLE AUTHORIZATION ERROR: INVALID_REQUEST" and sampleApp exit.
## Provide the steps to reproduce the issue, if applicable:

run the command
`./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json ../third-party/alexa-rpi/models`
then below is the result
`2018-04-30 17:21:17.442 [  1] I sdkVersion: 1.7.0
configFile ./Integration/AlexaClientSDKConfig.json
#################################################
#       NOTIFICATION INDICATOR STATE: OFF       #
#################################################

ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.front.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
                  #    #     #  #####      #####  ######  #    #              
                 # #   #     # #     #    #     # #     # #   #               
                #   #  #     # #          #       #     # #  #                
               #     # #     #  #####      #####  #     # ###                 
               #######  #   #        #          # #     # #  #                
               #     #   # #   #     #    #     # #     # #   #               
               #     #    #     #####      #####  ######  #    #              
                                                                              
       #####                                           #                      
      #     #   ##   #    # #####  #      ######      # #   #####  #####      
      #        #  #  ##  ## #    # #      #          #   #  #    # #    #     
       #####  #    # # ## # #    # #      #####     #     # #    # #    #     
            # ###### #    # #####  #      #         ####### #####  #####      
      #     # #    # #    # #      #      #         #     # #      #          
       #####  #    # #    # #      ###### ######    #     # #      #          

       SDK Version 1.7.0

+----------------------------------------------------------------------------+
|                                  Options:                                  |
| Wake word:                                                                 |
|       Simply say Alexa and begin your query.                               |
| Tap to talk:                                                               |
|       Press 't' and Enter followed by your query (no need for the 'Alexa').|
| Hold to talk:                                                              |
|       Press 'h' followed by Enter to simulate holding a button.            |
|       Then say your query (no need for the 'Alexa').                       |
|       Press 'h' followed by Enter to simulate releasing a button.          |
| Stop an interaction:                                                       |
|       Press 's' and Enter to stop an ongoing interaction.                  |
| Privacy mode (microphone off):                                             |
|       Press 'm' and Enter to turn on and off the microphone.               |
| Echo Spatial Perception (ESP): This is for testing purpose only!           |
|       Press 'e' followed by Enter at any time to adjust ESP settings.      |
| Playback Controls:                                                         |
|       Press '1' for a 'PLAY' button press.                                 |
|       Press '2' for a 'PAUSE' button press.                                |
|       Press '3' for a 'NEXT' button press.                                 |
|       Press '4' for a 'PREVIOUS' button press.                             |
| Settings:                                                                  |
|       Press 'c' followed by Enter at any time to see the settings screen.  |
| Speaker Control:                                                           |
|       Press 'p' followed by Enter at any time to adjust speaker settings.  |
| Firmware Version:                                                          |
|       Press 'f' followed by Enter at any time to report a different        |
|       firmware version.                                                    |
| Info:                                                                      |
|       Press 'i' followed by Enter at any time to see the help screen.      |
| Reset device:                                                              |
|       Press 'k' followed by Enter at any time to reset your device. This   |
|       will erase any data stored in the device and you will have to        |
|       register your device with another account.                           |
|       This will kill the application since we don't support login yet.     |
| Quit:                                                                      |
|       Press 'q' followed by Enter at any time to quit the application.     |
+----------------------------------------------------------------------------+

##################################################################
#       UNRECOVERABLE AUTHORIZATION ERROR: INVALID_REQUEST       #
##################################################################`
### What version of the AVS Device SDK are you using?
      avs 1.7

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [yes ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ yes] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by piesquared** [comment]
I'm getting the same issue here. Just installed the 1.7.0 SDK on a fresh Raspbian Stretch setup and get the same error. Exact output below. Any help would be much appreciated.

```
2018-04-30 19:10:14.926 [  3] I InProcessAttachmentReader:readFailed:reason=SDS is closed
2018-04-30 19:10:14.926 [  3] 5 InternetConnectionMonitor:updateConnectionStatus:connected=true
2018-04-30 19:10:14.926 [  3] 5 InternetConnectionMonitor:notifyObserversLocked
2018-04-30 19:10:20.724 [  2] 5 HttpPost:doPostSucceeded:code=400
2018-04-30 19:10:20.724 [  2] 5 CBLAuthDelegate:receiveTokenResponse:code=400
2018-04-30 19:10:20.724 [  2] 5 CBLAuthDelegate:mapHTTPStatusToError:code=400,error=INVALID_REQUEST
2018-04-30 19:10:20.725 [  2] 5 CBLAuthDelegate:errorInLwaResponseBody:error=invalid_request,errorCode=INVALID_REQUEST
2018-04-30 19:10:20.725 [  2] 5 CBLAuthDelegate:setAuthError:authError=INVALID_REQUEST
2018-04-30 19:10:20.725 [  2] 0 CBLAuthDelegate:receiveTokenResponseFailed:result=INVALID_REQUEST
2018-04-30 19:10:20.725 [  2] 5 CBLAuthDelegate:setAuthState:newAuthState=UNRECOVERABLE_ERROR
2018-04-30 19:10:20.725 [  2] 9 CBLAuthDelegate:callingOnAuthStateChange:state=UNRECOVERABLE_ERROR,error=INVALID_REQUEST
##################################################################
#       UNRECOVERABLE AUTHORIZATION ERROR: INVALID_REQUEST       #
##################################################################

2018-04-30 19:10:20.726 [  9] E DCFDelegate:getAuthTokenFailed:reason=Unrecoverable error by auth delegate
2018-04-30 19:10:20.726 [  2] 5 CBLAuthDelegate:handleStopping
pure virtual method called
terminate called without an active exception
startsample.sh: line 3: 11180 Aborted                 ./SampleApp "/home/pi/build/Integration/AlexaClientSDKConfig.json" "/home/pi/third-party/alexa-rpi/models" DEBUG9
```

**Comment by frozenberg** [comment]
Hi @yexin123987,

To fix this problem, you should take two steps:

1. Remove the CBL database file you are using. This will let the SDK prepare a fresh, uncorrupted database file.
2. Make sure the value of `clientId` in your `AlexaClientSDKConfig.json` file is the clientId found under  the **Other devices and platforms** tab on developer.amazon.com, not the one found under the **Web** tab

**Comment by piesquared** [comment]
That fixed it for me - thanks a lot @frozenberg

**Comment by yexin123987** [comment]
@frozenberg Thanks for your comments. Does 'remove the CBL database' means remove the cblauthdelegate.db file in skd/application-necessities folder. I removed cblauthdelegate.db, but still got the same error...

**Comment by frozenberg** [comment]
You should remove the file that is pointed to by your `AlexaClientSDKConfig.json` under cblAuthDelegate. 

Have you also changed your clientId?

**Comment by rickysoung** [comment]
##################################################
#       Checking for authorization (15)...       #
##################################################

2018-05-02 10:32:03.383 [  2] 5 HttpPost:doPostSucceeded:code=200
2018-05-02 10:32:03.383 [  2] 5 CBLAuthDelegate:receiveTokenResponse:code=200
2018-05-02 10:32:03.383 [  2] 5 CBLAuthDelegate:mapHTTPStatusToError:code=200,error=SUCCESS
2018-05-02 10:32:03.383 [  2] 5 CBLAuthDelegate:setAuthError:authError=SUCCESS
2018-05-02 10:32:03.383 [  2] 5 CBLAuthDelegate:setRefreshToken
2018-05-02 10:32:03.383 [  2] 5 SQLiteCBLAuthDelegateStorage:setRefreshToken
2018-05-02 10:32:03.411 [  2] 5 CBLAuthDelegate:handleRefreshingToken
2018-05-02 10:32:03.411 [  2] 5 CBLAuthDelegate:requestRefresh
**2018-05-02 10:32:03.648 [  2] 5 HttpPost:doPostSucceeded:code=400
2018-05-02 10:32:03.648 [  2] 5 CBLAuthDelegate:receiveTokenResponse:code=400
2018-05-02 10:32:03.648 [  2] 5 CBLAuthDelegate:mapHTTPStatusToError:code=400,error=INVALID_REQUEST**
2018-05-02 10:32:03.648 [  2] 5 CBLAuthDelegate:errorInLwaResponseBody:error=invalid_request,errorCode=INVALID_REQUEST
2018-05-02 10:32:03.648 [  2] 5 CBLAuthDelegate:setAuthError:authError=INVALID_REQUEST
2018-05-02 10:32:03.648 [  2] 0 CBLAuthDelegate:receiveTokenResponseFailed:result=INVALID_REQUEST
2018-05-02 10:32:03.648 [  2] 5 CBLAuthDelegate:setAuthState:newAuthState=UNRECOVERABLE_ERROR
2018-05-02 10:32:03.649 [  2] 9 CBLAuthDelegate:callingOnAuthStateChange:state=UNRECOVERABLE_ERROR,error=INVALID_REQUEST
2018-05-02 10:32:03.649 [  2] 5 CBLAuthDelegate:handleStopping
##################################################################
#       UNRECOVERABLE AUTHORIZATION ERROR: INVALID_REQUEST       #
##################################################################

2018-05-02 10:32:03.651 [0] W RequiresShutdown:ShutdownMonitor:reason=no shutdown() call,name: =VisualActivityTracker
2018-05-02 10:32:03.651 [0] W RequiresShutdown:ShutdownMonitor:reason=never deleted,name=VisualActivityTracker
2018-05-02 10:32:03.651 [0] W RequiresShutdown:ShutdownMonitor:reason=no shutdown() call,name: =AVSConnectionManager
2018-05-02 10:32:03.651 [0] W RequiresShutdown:ShutdownMonitor:reason=never deleted,name=AVSConnectionManager
pure virtual method called
terminate called without an active exception
startsample.sh: line 3:  2562 Aborted                 ./SampleApp "/home/pi/build/Integration/AlexaClientSDKConfig.json" "/home/pi/third-party/alexa-rpi/models" DEBUG9

**Comment by yexin123987** [comment]
@frozenberg Updated clientID, fixed now. Thank you for the help.

**Comment by mikeluebke** [comment]
I am having a similar issue showing the same errors. I have double checked the client id, even made a new one and tried that. did not fix. I have deleted the CBL database file that has not fixed the issue either. Any ideas?
